name: study_app
description: Um aplicativo inteligente de estudos com IA e revisão espaçada
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  timezone: ^0.9.3 # Adicione esta linha


  # UI e Material Design
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.11.1

  # Navegação
  go_router: ^16.0.0

  # Gerenciamento de Estado
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP e API
  http: ^1.1.2
  dio: ^5.4.0

  # Armazenamento Local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilitários

  uuid: ^4.2.1

  # Imagens e Mídia
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Markdown
  flutter_markdown: ^0.7.7+1
  markdown: ^7.1.1

  # Autenticação
  jwt_decoder: ^2.0.1

  # Notificações
  flutter_local_notifications: ^17.1.2 # Use a versão estável mais recente

  # Animações
  lottie: ^3.3.1

  # Formulários
  flutter_form_builder: ^10.1.0
  intl: ^0.20.0


  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

